### ISSUE TITLE
CryptoJS: There is a bug with CryptoJS which makes the Chrome Browser to crash if the encrypted chunk is larger than 16MB

### ISSUE THREAD

**Issue by delian** [bivol/cryptarsi#5]
CryptoJS: There is a bug with CryptoJS which makes the Chrome Browser to crash if the encrypted chunk is larger than 16MB. For the moment we do assume our files will be smaller, but this bug needs some investigation and fix

**Comment by delian** [comment]
The browser crash if there is an allocation of a typed array with size larger than 16-100MB (depending on platform and available memory). We cannot avoid this problem, so we have implemented chunks to split the file in small pieces and not having a need of large typed arrays

**Comment by Tructivity** [comment]
Can you please give me the source code of this implementation because I couldn't encrypt large files and crash my chrome browser?
